<?php

declare(strict_types=1);

namespace Database\SoftDelete\Doctrine\Schema;

use Database\SoftDelete\Core\Attribute\SoftDeleteUniqueIndex;
use Database\SoftDelete\Core\Contract\SoftDeleteSchemaDefiner;
use Database\SoftDelete\Core\Contract\SoftDeletableInterface;
use Database\SoftDelete\Core\SoftDeleteNames;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Schema\Table;
use Doctrine\DBAL\Types\Types;
use Doctrine\Migrations\Provider\SchemaProvider;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\SchemaTool;

class SoftDeleteSchemaProvider implements SchemaProvider
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        private readonly SoftDeleteSchemaDefiner $schemaDefiner,
    ) {}

    public function createSchema(): Schema
    {
        // Build base schema from ORM metadata
        $metadataList = $this->entityManager->getMetadataFactory()->getAllMetadata();
        $schemaTool = new SchemaTool($this->entityManager);
        $schema = $schemaTool->getSchemaFromMetadata($metadataList);

        foreach ($metadataList as $metadata) {
            if (!$schema->hasTable($metadata->getTableName())) {
                continue;
            }

            $reflectionEntity = $metadata->getReflectionClass();
            $isSoftDeleted = $reflectionEntity?->implementsInterface(SoftDeletableInterface::class);
            $uniqueIndexAttr = $reflectionEntity?->getAttributes(SoftDeleteUniqueIndex::class);
            if (!$isSoftDeleted || !$uniqueIndexAttr) {
                continue;
            }

            /** @var SoftDeleteUniqueIndex $attribute */
            $attribute = $uniqueIndexAttr[0]->newInstance();
            $table = $schema->getTable($metadata->getTableName());
            $this->addGeneratedColumn($table);
            $this->addUniqueIndex($table, $attribute);
        }

        return $schema;
    }

    private function addGeneratedColumn(Table $table): void
    {
        if ($table->hasColumn(SoftDeleteNames::AUTO_GENERATED_COLUMN_NAME)) {
            return;
        }

        $table->addColumn(
            SoftDeleteNames::AUTO_GENERATED_COLUMN_NAME,
            Types::BOOLEAN,
            $this->schemaDefiner->getAutogeneratedColumnDefinition(),
        );
    }

    private function addUniqueIndex(Table $table, SoftDeleteUniqueIndex $attribute): void
    {
        $uniqueFields = array_unique(
            array_filter(
                $attribute->fields,
                fn($field) => $field && $field !== SoftDeleteNames::SOFT_DELETE_COLUMN_NAME,
            ),
        );

        if (empty($uniqueFields)) {
            return;
        }

        $indexName = $this->schemaDefiner->getAutogeneratedIndexName($table->getName(), $uniqueFields);
        if (!$table->hasIndex($indexName)) {
            $columns = array_merge($uniqueFields, [SoftDeleteNames::AUTO_GENERATED_COLUMN_NAME]);
            $table->addUniqueIndex($columns, $indexName);
        }
    }
}
