services:
  dsd-app:
    image: chrisbaltazar/symfony-php-8.1
    container_name: dsd-demo-app
    restart: unless-stopped
    volumes:
      - ./demo:/var/www/html
      - ./docker-entrypoint.sh:/entrypoint.sh:ro
      - ./composer.json:/var/www/doctrine-soft-delete/composer.json:ro
      - ./config:/var/www/doctrine-soft-delete/config
      - ./src:/var/www/doctrine-soft-delete/src
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    networks:
      - dsd-network

  dsd-mysql:
    image: mysql:8.0
    container_name: dsd-demo-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo_soft_delete
    ports:
      - "3333:3306"
    networks:
      - dsd-network

networks:
  dsd-network:
    driver: bridge