<?php

declare(strict_types=1);

namespace Database\SoftDelete\Engine\Mysql;

use Database\SoftDelete\Core\Contract\SoftDeleteSchemaDefiner;
use Database\SoftDelete\Core\SoftDeleteNames;
use Doctrine\DBAL\Schema\Column;

class MySQLSchemaDefiner implements SoftDeleteSchemaDefiner
{
    public function getAutogeneratedColumnDefinition(): array
    {
        return [
            'notnull' => true,
            'columnDefinition' => $this->buildColumnDefinition(),
        ];
    }

    public function getAutogeneratedIndexName(string $table, array $fields): string
    {
        $idxName = sprintf(
            '%s_%s_%s_%s',
            SoftDeleteNames::UNIQUE_INDEX_PREFIX,
            $table,
            implode('_', $fields),
            uniqid('', false),
        );

        // MySQL max identifier length = 64
        if (strlen($idxName) <= 64) {
            return $idxName;
        }

        // If too long, hash it deterministically
        return sprintf('%s_%s', substr($idxName, 0, 40), substr(md5($idxName), 0, 16));
    }

    public function isAutogeneratedColumn(Column $column): bool
    {
        return $column->getColumnDefinition() === $this->buildColumnDefinition();
    }

    private function buildColumnDefinition(): string
    {
        return sprintf(
            'TINYINT(1) GENERATED ALWAYS as (%s IS NULL) STORED',
            SoftDeleteNames::SOFT_DELETE_COLUMN_NAME,
        );
    }
}