<?php

declare(strict_types=1);

namespace Database\SoftDelete\Engine\Mysql;

use Database\SoftDelete\Core\SoftDeleteNames;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Platforms\MySQL\Comparator as MySQLComparator;
use Doctrine\DBAL\Schema\Column;
use Doctrine\DBAL\Schema\ColumnDiff;
use Doctrine\DBAL\Schema\Comparator as BaseComparator;
use Doctrine\DBAL\Schema\Table;
use Doctrine\DBAL\Schema\TableDiff;

class SoftDeleteMySQLComparator extends BaseComparator
{
    public function __construct(
        AbstractPlatform $platform,
        private readonly MySQLComparator $inner,
        private readonly MySQLSchemaDefiner $schemaHandler,
    ) {
        parent::__construct($platform);
    }

    public function compareTables(Table $oldTable, Table $newTable): TableDiff
    {
        $diff = $this->inner->compareTables($oldTable, $newTable);
        $changedCols = $diff->getChangedColumns();
        /** @var ColumnDiff $column */
        foreach ($changedCols as $name => $column) {
            if (
                !$this->isAutoGeneratedColumn($name, $column->getOldColumn())
                && !$this->isAutoGeneratedColumn($name, $column->getNewColumn())
            ) {
                continue;
            }

            // After validated colum definition matches the expected data, we can assume is the same and discard unwanted changes
            unset($changedCols[$name]);
        }

        $renamedIdx = $diff->getRenamedIndexes();
        foreach ($renamedIdx as $name => $index) {
            if (str_starts_with($name, SoftDeleteNames::UNIQUE_INDEX_PREFIX)) {
                unset($renamedIdx[$name]);
            }
        }

        return new TableDiff(
            $diff->getOldTable(),
            $diff->getAddedColumns(),
            $changedCols,
            $diff->getDroppedColumns(),
            $diff->getAddedIndexes(),
            $diff->getModifiedIndexes(),
            $diff->getDroppedIndexes(),
            $renamedIdx,
            $diff->getAddedForeignKeys(),
            $diff->getModifiedForeignKeys(),
            $diff->getDroppedForeignKeys(),
        );
    }

    private function isAutoGeneratedColumn(string $name, Column $column): bool
    {
        return $name === SoftDeleteNames::AUTO_GENERATED_COLUMN_NAME
            && $this->schemaHandler->isAutoGeneratedColumn($column);
    }
}