services:
  _defaults:
    autowire: true
    autoconfigure: true

  Database\SoftDelete\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/SoftDeleteBundle.php'

  Database\SoftDelete\Doctrine\Schema\SoftDeleteSchemaProvider:
    factory: '@Database\SoftDelete\Core\Factory\SoftDeleteSchemaProviderFactory'

  