<?php

declare(strict_types=1);

namespace Database\SoftDelete\Core\Contract;

use Doctrine\DBAL\Schema\Column;

interface SoftDeleteSchemaDefiner
{
    public function getAutogeneratedColumnDefinition(): array;

    public function getAutogeneratedIndexName(string $table, array $fields): string;

    public function isAutogeneratedColumn(Column $column): bool;
}